default:
  golem_name: recruitrankingsapp
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/jerri/OneDrive/Documents/R/Campus2Canton/recruit_rankings_app
